### ISSUE TITLE
humble bundle api json decode error

### ISSUE THREAD

**Issue by RABijl** [talonius/hb-downloader#28]
I'm getting an error trying to list or download a humblebundle. My guess is that the api has changed since part of the full output is html, but the short stack trace is this: 

```
Traceback (most recent call last):
  File "/home/shmoopy/virtualenvs/general-env/lib/python3.10/site-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

This still worked fine two months ago, leading me to believe it was a recent change.

**Comment by jacroe** [comment]
I had the same error occur a few minutes ago. I was able to resolve it by re-grabbing my current `session-cookie` and saving it.
