### ISSUE TITLE
Login fails if a captcha is requested

### ISSUE THREAD

**Issue by skitt** [talonius/hb-downloader#6]
When attempting to log in, I now get (after entering my Authy token)

    Traceback (most recent call last):
      File "./hb-downloader.py", line 41, in <module>
        hapi.login(ConfigData.username, ConfigData.password, ConfigData.authy_token)
      File "/home/steve/Debian/hb-downloader-git/humble_api/humble_api.py", line 133, in login
        error_msg, request=request, response=response, authy_required=authy_required)
    humble_api.exceptions.humble_captcha_exception.HumbleCaptchaException: Please answer the CAPTCHA

**Comment by talonius** [comment]
I don't have any way to solve the CAPTCHA (if I did, I'd be a millionaire) and since we're dealing with terminal output I don't have any method of opening a display for the user to solve.  Generally, they only request CAPTCHAs when you've been logging in repeatedly or incorrectly.  Logging in a few times manually via their web site will reset the timer.

I could die better by detecting the CAPTCHA and outputting a message that a CAPTCHA is being requested; please log in manually to help clear the CAPTCHA required flag.

**Comment by stefan2904** [comment]
I can confirm, after successfully logging in, I get a `HumbleCaptchaException`. Maybe displaying a link to the Captcha (image) should do the job?

**Comment by talonius** [comment]
A link would be about the best I can do.  I'll see what I can do in that regard.

**Comment by L-K-M** [comment]
You can force a Captcha to appear in your browser when you use Incognito mode. Apparently, it uses a cookie to determine whether you need a captcha.

Unfortunately, the Captcha you get isn't just an image; it's some kind of interactive "game" where you need to click on squares that contain certain things, so just showing a link to an image won't fix the issue.

**Comment by alexdelifer** [comment]
Any chance you could post the syntax or censored version of the cookies.txt so I can fill it in from cookies I exported from firefox, simply copying the exported cookies did not work, or am I on the wrong track here... 
I just can't seem to please the captcha gods.
