### ISSUE TITLE
Crashes on launch

### ISSUE THREAD

**Issue by cyotee** [talonius/hb-downloader#7]
python hb-downloader.py
The Clown's Humble Bundle Downloader v0.41

This downloader includes MIT licensed code from Joel Pedraza.
https://github.com/saik0/humblebundle-python

[2017/09/03 08:47:52] [    Config] write_md5=True
[2017/09/03 08:47:52] [    Config] read_md5=True
[2017/09/03 08:47:52] [    Config] force_md5=False
[2017/09/03 08:47:52] [    Config] ignore_md5=False
[2017/09/03 08:47:52] [    Config] debug=True
[2017/09/03 08:47:52] [    Config] download_location=/Volumes/AFP-thearchive/thevault/Unsorted/Humble Bundle/
[2017/09/03 08:47:52] [    Config] cookie_filename=/Applications/hb-downloader/cookies.txt
[2017/09/03 08:47:52] [    Config] chunksize=8192000
[2017/09/03 08:47:52] [    Config] resume_downloads=True
[2017/09/03 08:47:52] [    Config] Platform asmjs=False
[2017/09/03 08:47:52] [    Config] Platform mac=True
[2017/09/03 08:47:52] [    Config] Platform audio=True
[2017/09/03 08:47:52] [    Config] Platform linux=True
[2017/09/03 08:47:52] [    Config] Platform windows=True
[2017/09/03 08:47:52] [    Config] Platform android=True
[2017/09/03 08:47:52] [    Config] Platform ebook=True
Enter your Authy token:
Traceback (most recent call last):
  File "hb-downloader.py", line 41, in <module>
    hapi.login(ConfigData.username, ConfigData.password, ConfigData.authy_token)
  File "/Applications/hb-downloader/humble_api/humble_api.py", line 115, in login
    data = self.__parse_data(response)
  File "/Applications/hb-downloader/humble_api/humble_api.py", line 255, in __parse_data
    raise HumbleParseException("Invalid JSON: %s", str(e), request=response.request, response=response)
humble_api.exceptions.humble_parse_exception.HumbleParseException: [Errno Invalid JSON: %s] Extra data: line 1 column 5 - line 5 column 2 (char 4 - 77)

**Comment by cyotee** [comment]
# download-location: /mnt/Storage/HumbleBundle/Games/
cookie-filename: /Applications/hb-downloader/cookies.txt
username: <I put in my login>
password: <I put in my password>
download-location: /Volumes/AFP-thearchive/thevault/Unsorted/Humble Bundle/
chunk-size: 8192000
force_md5: False
write_md5: True
read_md5: True
debug: True

default_headers:
  Accept: application/json
  Accept-Charset: utf-8
  Keep-Alive: True
  X-Requested-By: hb_android_app
  User-Agent: Apache-HttpClient/UNAVAILABLE (java 1.4)

default_params:
  ajax: True

download-platforms:
  audio: True
  ebook: True
  windows: True
  mac: True
  linux: True
  android: True
  asmjs: False

**Comment by cyotee** [comment]
#LWP-Cookies-2.0

Set-Cookie3: _simpleauth_sess="<The Key I found my taking the _simpleauth_sess value for the www.humblebundle.com cookie"; path="/"; domain="www.humblebundle.com"; path_spec; secure; expires="2018-08-27 22:41:21Z"; HttpOnly=None; version=0

**Comment by jesdynf** [comment]
I get the same thing, Python 2.7.13.

**Comment by talonius** [comment]
I'm going to have to release a new version which will save the invalid responses from Humble Bundle so they can be examined for what's going wrong.  I'll take care of that this weekend, work permitting.

**Comment by Obererpel** [comment]
Did you release the bugfix for this? I can not find it.
