### ISSUE TITLE
[Errno Invalid JSON: %s] Extra data

### ISSUE THREAD

**Issue by fangfufu** [talonius/hb-downloader#9]
I get the following errors

````
Traceback (most recent call last):
  File "hb-downloader.py", line 41, in <module>
    hapi.login(ConfigData.username, ConfigData.password, ConfigData.authy_token)
  File "/home/fangfufu/src/hb-downloader/humble_api/humble_api.py", line 115, in login
    data = self.__parse_data(response)
  File "/home/fangfufu/src/hb-downloader/humble_api/humble_api.py", line 255, in __parse_data
    raise HumbleParseException("Invalid JSON: %s", str(e), request=response.request, response=response)
humble_api.exceptions.humble_parse_exception.HumbleParseException: [Errno Invalid JSON: %s] Extra data: line 1 column 5 - line 5 column 2 (char 4 - 77)
````
I have tried using the cookies.txt

**Comment by vonkoda** [comment]
Exactly the same problem, also tried importing a cookies.txt file to no avail.

**Comment by Two-Tone** [comment]
Same here. 

And with IGN now owning HB, now is the best time to backup your HB library.

**Comment by Kirk1984** [comment]
I'll chime in with a "Same here" too.

Tried it on Arch with python2, everything configured but i get the same error.

@Two-Tone Exactly what i think ;)

**Comment by ZaraFrax** [comment]
a guy on reddit solved it 
https://www.reddit.com/r/DataHoarder/comments/76aq7d/ign_now_owns_humble_bundle_anyone_know_of_any/dod6qbh/

**Comment by Kirk1984** [comment]
@ZaraFrax I guess i'm too stupid for the solution. I tried for 2 hours with no luck. I saw that on the subreddit but somehow i don't get it working.

**Comment by MayeulC** [comment]
Forked and implemented the above solution at https://github.com/MayeulC/hb-downloader

You can pass the cookie as an argument or set it in the config file. Hopefuly Authy works as well, but I didn't try.

Thank you for the hint.

I also converted it to python3 in the process, as it helped with development tools I had already installed. That might not have been the brightest idea, as there are now other bugs due to this, which I am fixing slowly. But it seems to be working pretty well for now :)

**Comment by fengshaun** [comment]
Good job. Since it looks like you're taking over the development, you can also do something about the frequent HB session invalidation. Have a look at the BeautifulSoup module. I'm not sure if HumbleBundle relies on the cookie expiry to invalidate the session or not.

**Comment by MayeulC** [comment]
Hello there,
I don't really want to commit myself to this, although I can try to maintain it a bit.
Non-critical improvements will have to wait, as all I have at my disposal for now is a 2007 ultrabook with a slow atom processor, which makes web development really painful :D

2to3 was used for the conversion process, but it produced some invalid code in places.

**Comment by Two-Tone** [comment]
I can confirm that Humble Bundle doesn't cheek the date of the cookie. The
date set for my cookie was in 2019 but I used 1700000000, which is in 2023.
Still works.

**Comment by crsleeth** [comment]
Still getting the captcha error even with the processlogin change and cookies.txt and authy set up. Can anyone confirm this still works?
